name: iOS CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Use a macOS runner for iOS builds

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the app
        run: xcodebuild clean build -project SuperJak.xcodeproj -scheme SuperJak -destination 'platform:visionOS Simulator,OS:1.2,name:Apple Vision Pro' 
